In [103]:
import pandas as pd
import warnings

warnings.filterwarnings("ignore")

# Set option to show all columns
pd.set_option('display.max_columns', None)

In [104]:
# Loading the global terrorism
globalterrorism_df = pd.read_csv("../datasets/globalterrorism.csv", encoding="ISO-8859-1", lineterminator="\n")

# Verify it's columns
globalterrorism_df.head()

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,region_txt,provstate,city,latitude,longitude,specificity,vicinity,location,summary,crit1,crit2,crit3,doubtterr,alternative,alternative_txt,multiple,success,suicide,attacktype1,attacktype1_txt,attacktype2,attacktype2_txt,attacktype3,attacktype3_txt,targtype1,targtype1_txt,targsubtype1,targsubtype1_txt,corp1,target1,natlty1,natlty1_txt,targtype2,targtype2_txt,targsubtype2,targsubtype2_txt,corp2,target2,natlty2,natlty2_txt,targtype3,targtype3_txt,targsubtype3,targsubtype3_txt,corp3,target3,natlty3,natlty3_txt,gname,gsubname,gname2,gsubname2,gname3,gsubname3,motive,guncertain1,guncertain2,guncertain3,individual,nperps,nperpcap,claimed,claimmode,claimmode_txt,claim2,claimmode2,claimmode2_txt,claim3,claimmode3,claimmode3_txt,compclaim,weaptype1,weaptype1_txt,weapsubtype1,weapsubtype1_txt,weaptype2,weaptype2_txt,weapsubtype2,weapsubtype2_txt,weaptype3,weaptype3_txt,weapsubtype3,weapsubtype3_txt,weaptype4,weaptype4_txt,weapsubtype4,weapsubtype4_txt,weapdetail,nkill,nkillus,nkillter,nwound,nwoundus,nwoundte,property,propextent,propextent_txt,propvalue,propcomment,ishostkid,nhostkid,nhostkidus,nhours,ndays,divert,kidhijcountry,ransom,ransomamt,ransomamtus,ransompaid,ransompaidus,ransomnote,hostkidoutcome,hostkidoutcome_txt,nreleased,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related\r
0,197000000001,1970,7,2,NaN,0,NaN,58,Dominican Republic,2,Central America & Caribbean,NaN,Santo Domingo,18.456792,-69.951164,1.0,0,NaN,NaN,1,1,1,0.0,NaN,NaN,0.0,1,0,1,Assassination,NaN,NaN,NaN,NaN,14,Private Citizens & Property,68.0,Named Civilian,NaN,Julio Guzman,58.0,Dominican Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MANO-D,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,\r
1,197000000002,1970,0,0,NaN,0,NaN,130,Mexico,1,North America,Federal,Mexico city,19.371887,-99.086624,1.0,0,NaN,NaN,1,1,1,0.0,NaN,NaN,0.0,1,0,6,Hostage Taking (Kidnapping),NaN,NaN,NaN,NaN,7,Government (Diplomatic),45.0,"Diplomatic Personnel (outside of embassy, cons...",Belgian Ambassador Daughter,"Nadine Chaval, daughter",21.0,Belgium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23rd of September Communist League,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,NaN,Mexico,1.0,800000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PGIS,0,1,1,1,\r
2,197001000001,1970,1,0,NaN,0,NaN,160,Philippines,5,Southeast Asia,Tarlac,Unknown,15.478598,120.599741,4.0,0,NaN,NaN,1,1,1,0.0,NaN,NaN,0.0,1,0,1,Assassination,NaN,NaN,NaN,NaN,10,Journalists & Media,54.0,Radio Journalist/Staff/Facility,Voice of America,Employee,217.0,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,\r
3,197001000002,1970,1,0,NaN,0,NaN,78,Greece,8,Western Europe,Attica,Athens,37.997490,23.762728,1.0,0,NaN,NaN,1,1,1,0.0,NaN,NaN,0.0,1,0,3,Bombing/Explosion,NaN,NaN,NaN,NaN,7,Government (Diplomatic),46.0,Embassy/Consulate,NaN,U.S. Embassy,217.0,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,Explosives,16.0,Unknown Explosive Type,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Explosive,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,\r
4,197001000003,1970,1,0,NaN,0,NaN,101,Japan,4,East Asia,Fukouka,Fukouka,33.580412,130.396361,1.0,0,NaN,NaN,1,1,1,-9.0,NaN,NaN,0.0,1,0,7,Facility/Infrastructure Attack,NaN,NaN,NaN,NaN,7,Government (Diplomatic),46.0,Embassy/Consulate,NaN,U.S. Consulate,217.0,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,Incendiary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Incendiary,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,\r

In [105]:
# Check for null values in the dataset

pd.set_option("display.max_rows", None)  # Show all rows
pd.set_option("display.max_columns", None)  # Show all columns


# Calculate the percentage of null (NaN) values in each column
null_percentage = globalterrorism_df.isnull().mean() * 100

# Display the percentage of null values in each column
print(null_percentage)



# The following columns will be dropped due to redundancy, missing values, or low relevance:
# - approxdate: Not essential (attack date is already covered by iyear, imonth, iday)
# - resolution: Too many missing values, not useful for most analyses
# - location: Redundant (province/state & city already exist)
# - summary: Optional text description, can be removed for efficiency
# - alternative, alternative_txt: Rarely used, unclear relevance
# - related: Often missing, not crucial for most analyses
# - gsubname, gsubname2, gsubname3: Secondary group names, mostly empty
# - weaptype2, weaptype3, weaptype4: Most attacks involve a single weapon type
# - weapsubtype1, weapsubtype2, weapsubtype3, weapsubtype4: Detailed weapon breakdown, not always needed
# - weapdetail: Often missing, very specific information
# - claimmode, claimmode2, claimmode3: Claim details, frequently unavailable
# - propextent, propvalue, propcomment: Property damage details, not essential
# - nhostkid, nhostkidus, nhours, ndays: Hostage data, often incomplete
# - ransom, ransomamt, ransompaid, ransompaidus: Ransom information, rare cases
# - hostkidoutcome, nreleased: Hostage outcomes, too many missing values
# - scite1, scite2, scite3: Citation sources, not useful for analysis

eventid                0.000000
iyear                  0.000000
imonth                 0.000000
iday                   0.000000
approxdate            94.914993
extended               0.000000
resolution            98.778145
country                0.000000
country_txt            0.000000
region                 0.000000
region_txt             0.000000
provstate              0.231712
city                   0.239417
latitude               2.507554
longitude              2.508104
specificity            0.003302
vicinity               0.000000
location              69.456385
summary               36.396409
crit1                  0.000000
crit2                  0.000000
crit3                  0.000000
doubtterr              0.000550
alternative           84.032781
alternative_txt       84.032781
multiple               0.000550
success                0.000000
suicide                0.000000
attacktype1            0.000000
attacktype1_txt        0.000000
attacktype2           96.524869
attacktype2_txt       96.524869
attacktype3           99.764435
attacktype3_txt       99.764435
targtype1              0.000000
targtype1_txt          0.000000
targsubtype1           5.709144
targsubtype1_txt       5.709144
corp1                 23.419982
target1                0.351146
natlty1                0.858050
natlty1_txt            0.858050
targtype2             93.866510
targtype2_txt         93.866510
targsubtype2          94.119136
targsubtype2_txt      94.119136
corp2                 94.431755
target2               93.934757
natlty2               94.040431
natlty2_txt           94.040431
targtype3             99.352747
targtype3_txt         99.352747
targsubtype3          99.396228
targsubtype3_txt      99.396228
corp3                 99.435305
target3               99.353298
natlty3               99.368708
natlty3_txt           99.368708
gname                  0.000000
gsubname              96.758232
gname2                98.892075
gsubname2             99.911938
gname3                99.821675
gsubname3             99.988992
motive                72.171984
guncertain1            0.209146
guncertain2           98.923997
guncertain3           99.823877
individual             0.000000
nperps                39.140629
nperpcap              38.245703
claimed               36.391456
claimmode             89.497003
claimmode_txt         89.497003
claim2                98.959772
claimmode2            99.660963
claimmode2_txt        99.660963
claim3                99.824978
claimmode3            99.926799
claimmode3_txt        99.926799
compclaim             97.336687
weaptype1              0.000000
weaptype1_txt          0.000000
weapsubtype1          11.430396
weapsubtype1_txt      11.430396
weaptype2             92.775096
weaptype2_txt         92.775096
weapsubtype2          93.647456
weapsubtype2_txt      93.647456
weaptype3             98.974633
weaptype3_txt         98.974633
weapsubtype3          99.068198
weapsubtype3_txt      99.068198
weaptype4             99.959822
weaptype4_txt         99.959822
weapsubtype4          99.961473
weapsubtype4_txt      99.961473
weapdetail            37.244553
nkill                  5.676120
nkillus               35.470111
nkillter              36.852678
nwound                 8.977330
nwoundus              35.611010
nwoundte              38.055270
property               0.000000
propextent            64.739585
propextent_txt        64.739585
propvalue             78.541039
propcomment           68.100236
ishostkid              0.097969
nhostkid              92.530175
nhostkidus            92.560446
nhours                97.763786
ndays                 95.528672
divert                99.821675
kidhijcountry         98.180978
ransom                57.410659
ransomamt             99.256980
ransomamtus           99.690133
ransompaid            99.574002
ransompaidus          99.696187
ransomnote            99.718203
hostkidoutcome        93.950719
hostkidoutcome_txt    93.950719
nreleased             94.275996
addnotes              84.430159
scite1                36.430533
scite2                57.657231
scite3                76.049447
dbsource               0.000000
INT_LOG                0.000000
INT_IDEO               0.000000
INT_MISC               0.000000
INT_ANY                0.000000
related\r              0.000000
dtype: float64

In [106]:
columns_to_drop = [
    "approxdate", "resolution", "location", "summary", "alternative", "alternative_txt",
    "gsubname", "gsubname2", "gsubname3", "weaptype2", "weaptype3", "weaptype4",
    "weapsubtype1", "weapsubtype2", "weapsubtype3", "weapsubtype4", "weapdetail",
    "claimmode", "claimmode2", "claimmode3", "propextent", "propvalue", "propcomment",
    "nhostkid", "nhostkidus", "nhours", "ndays", "ransom", "ransomamt", "ransompaid", "ransompaidus",
    "ransomnote", "hostkidoutcome", "nreleased", "scite1", "scite2", "scite3", "addnotes","INT_LOG",
    "INT_IDEO",	"INT_MISC",	"INT_ANY","country", "region",
    
    # Additional columns with >60% missing data
    "targtype2", "targtype2_txt", "targsubtype2", "targsubtype2_txt", "corp2", "target2", "natlty2", "natlty2_txt",
    "targtype3", "targtype3_txt", "targsubtype3", "targsubtype3_txt", "corp3", "target3", "natlty3", "natlty3_txt",
    "guncertain2", "guncertain3", "claim2", "claimmode2", "claimmode2_txt", "claim3", "claimmode3", "claimmode3_txt",
    "weaptype2", "weaptype2_txt", "weapsubtype2", "weapsubtype2_txt", "weaptype3", "weaptype3_txt", "weapsubtype3", "weapsubtype3_txt",
    "weaptype4", "weaptype4_txt", "weapsubtype4", "weapsubtype4_txt", "ransomamtus", "ransomnote"
]


globalterrorism_df.drop(columns=columns_to_drop, inplace=True)

In [107]:
# List of columns with missing values (excluding those in columns_to_drop)
columns_with_missing = [
    'provstate', 'city', 'latitude', 'longitude', 'specificity', 'doubtterr', 
    'targsubtype1', 'corp1', 'target1', 'natlty1', 'natlty1_txt', 'targsubtype1_txt',
    'nperps', 'nperpcap', 'claimed', 'nkill', 'nkillus', 'nkillter', 'nwound', 'nwoundus', 
    'nwoundte', 'property', 'ishostkid', 'guncertain1', 'individual', 'attacktype2', 'attacktype2_txt', 'attacktype3', 'attacktype3_txt',
    'gname2', 'gname3', 'motive', 'claimmode_txt', 'compclaim', 
    'divert', 'kidhijcountry', 'hostkidoutcome_txt'
]

# Fill numerical columns with the median or mean
numerical_columns = [
    'latitude', 'longitude', 'specificity', 'doubtterr', 'targsubtype1', 'nperps', 'nperpcap', 
    'claimed', 'nkill', 'nkillus', 'nkillter', 'nwound', 'nwoundus', 'nwoundte'
]

# Fill categorical columns with the mode (most frequent value)
categorical_columns = [
    'provstate', 'city', 'targsubtype1_txt', 'corp1', 'target1', 'natlty1', 'natlty1_txt', 
    'targsubtype1_txt', 'property', 'ishostkid', 'guncertain1', 'individual'
]

# Fill missing values in numerical columns with median (or mean if you prefer)
for col in numerical_columns:
    if col in globalterrorism_df.columns:
        globalterrorism_df[col] = globalterrorism_df[col].fillna(globalterrorism_df[col].median())

# Fill missing values in categorical columns with mode
for col in categorical_columns:
    if col in globalterrorism_df.columns:
        globalterrorism_df[col] = globalterrorism_df[col].fillna(globalterrorism_df[col].mode()[0])

# Check the filled columns
print(globalterrorism_df.isnull().sum())

eventid                    0
iyear                      0
imonth                     0
iday                       0
extended                   0
country_txt                0
region_txt                 0
provstate                  0
city                       0
latitude                   0
longitude                  0
specificity                0
vicinity                   0
crit1                      0
crit2                      0
crit3                      0
doubtterr                  0
multiple                   1
success                    0
suicide                    0
attacktype1                0
attacktype1_txt            0
attacktype2           175377
attacktype2_txt       175377
attacktype3           181263
attacktype3_txt       181263
targtype1                  0
targtype1_txt              0
targsubtype1               0
targsubtype1_txt           0
corp1                      0
target1                    0
natlty1                    0
natlty1_txt                0
gname                      0
gname2                179678
gname3                181367
motive                131130
guncertain1                0
individual                 0
nperps                     0
nperpcap                   0
claimed                    0
claimmode_txt         162608
compclaim             176852
weaptype1                  0
weaptype1_txt              0
weapsubtype1_txt       20768
nkill                      0
nkillus                    0
nkillter                   0
nwound                     0
nwoundus                   0
nwoundte                   0
property                   0
propextent_txt        117626
ishostkid                  0
divert                181367
kidhijcountry         178386
hostkidoutcome_txt    170700
dbsource                   0
related\r                  0
dtype: int64

In [108]:
# Calculate the percentage of NaN values in each column
nan_percentage = globalterrorism_df.isna().mean() * 100

# Display the percentage of NaN values in each column
print(nan_percentage)

eventid                0.000000
iyear                  0.000000
imonth                 0.000000
iday                   0.000000
extended               0.000000
country_txt            0.000000
region_txt             0.000000
provstate              0.000000
city                   0.000000
latitude               0.000000
longitude              0.000000
specificity            0.000000
vicinity               0.000000
crit1                  0.000000
crit2                  0.000000
crit3                  0.000000
doubtterr              0.000000
multiple               0.000550
success                0.000000
suicide                0.000000
attacktype1            0.000000
attacktype1_txt        0.000000
attacktype2           96.524869
attacktype2_txt       96.524869
attacktype3           99.764435
attacktype3_txt       99.764435
targtype1              0.000000
targtype1_txt          0.000000
targsubtype1           0.000000
targsubtype1_txt       0.000000
corp1                  0.000000
target1                0.000000
natlty1                0.000000
natlty1_txt            0.000000
gname                  0.000000
gname2                98.892075
gname3                99.821675
motive                72.171984
guncertain1            0.000000
individual             0.000000
nperps                 0.000000
nperpcap               0.000000
claimed                0.000000
claimmode_txt         89.497003
compclaim             97.336687
weaptype1              0.000000
weaptype1_txt          0.000000
weapsubtype1_txt      11.430396
nkill                  0.000000
nkillus                0.000000
nkillter               0.000000
nwound                 0.000000
nwoundus               0.000000
nwoundte               0.000000
property               0.000000
propextent_txt        64.739585
ishostkid              0.000000
divert                99.821675
kidhijcountry         98.180978
hostkidoutcome_txt    93.950719
dbsource               0.000000
related\r              0.000000
dtype: float64

In [109]:
# Calculate the percentage of missing values for each column
missing_percentage = globalterrorism_df.isnull().mean()

# Identify columns with more than 60% missing values
columns_to_drop = missing_percentage[missing_percentage > 0.60].index

# Drop the identified columns
globalterrorism_df = globalterrorism_df.drop(columns=columns_to_drop)

# Verify the changes
print(globalterrorism_df.isnull().sum())

eventid                 0
iyear                   0
imonth                  0
iday                    0
extended                0
country_txt             0
region_txt              0
provstate               0
city                    0
latitude                0
longitude               0
specificity             0
vicinity                0
crit1                   0
crit2                   0
crit3                   0
doubtterr               0
multiple                1
success                 0
suicide                 0
attacktype1             0
attacktype1_txt         0
targtype1               0
targtype1_txt           0
targsubtype1            0
targsubtype1_txt        0
corp1                   0
target1                 0
natlty1                 0
natlty1_txt             0
gname                   0
guncertain1             0
individual              0
nperps                  0
nperpcap                0
claimed                 0
weaptype1               0
weaptype1_txt           0
weapsubtype1_txt    20768
nkill                   0
nkillus                 0
nkillter                0
nwound                  0
nwoundus                0
nwoundte                0
property                0
ishostkid               0
dbsource                0
related\r               0
dtype: int64

In [110]:
# Fill missing values for numeric columns with 0 (or use another method as appropriate)
globalterrorism_df['weapsubtype1_txt'].fillna('Unknown', inplace=True)

# Alternatively, for other columns, you can fill missing values based on the column type
globalterrorism_df.fillna({
    'weapsubtype1_txt': 'Unknown',  # for categorical columns
    # You can add more columns if needed, with different strategies
}, inplace=True)

# Or you can use forward or backward filling for other columns
globalterrorism_df.fillna(method='ffill', inplace=True)

# Verify that all missing data is handled
print(globalterrorism_df.isnull().sum())

eventid             0
iyear               0
imonth              0
iday                0
extended            0
country_txt         0
region_txt          0
provstate           0
city                0
latitude            0
longitude           0
specificity         0
vicinity            0
crit1               0
crit2               0
crit3               0
doubtterr           0
multiple            0
success             0
suicide             0
attacktype1         0
attacktype1_txt     0
targtype1           0
targtype1_txt       0
targsubtype1        0
targsubtype1_txt    0
corp1               0
target1             0
natlty1             0
natlty1_txt         0
gname               0
guncertain1         0
individual          0
nperps              0
nperpcap            0
claimed             0
weaptype1           0
weaptype1_txt       0
weapsubtype1_txt    0
nkill               0
nkillus             0
nkillter            0
nwound              0
nwoundus            0
nwoundte            0
property            0
ishostkid           0
dbsource            0
related\r           0
dtype: int64

In [111]:
globalterrorism_df.head()

,eventid,iyear,imonth,iday,extended,country_txt,region_txt,provstate,city,latitude,longitude,specificity,vicinity,crit1,crit2,crit3,doubtterr,multiple,success,suicide,attacktype1,attacktype1_txt,targtype1,targtype1_txt,targsubtype1,targsubtype1_txt,corp1,target1,natlty1,natlty1_txt,gname,guncertain1,individual,nperps,nperpcap,claimed,weaptype1,weaptype1_txt,weapsubtype1_txt,nkill,nkillus,nkillter,nwound,nwoundus,nwoundte,property,ishostkid,dbsource,related\r
0,197000000001,1970,7,2,0,Dominican Republic,Central America & Caribbean,Baghdad,Santo Domingo,18.456792,-69.951164,1.0,0,1,1,1,0.0,0.0,1,0,1,Assassination,14,Private Citizens & Property,68.0,Named Civilian,Unknown,Julio Guzman,58.0,Dominican Republic,MANO-D,0.0,0,-99.0,0.0,0.0,13,Unknown,Unknown,1.0,0.0,0.0,0.0,0.0,0.0,0,0.0,PGIS,\r
1,197000000002,1970,0,0,0,Mexico,North America,Federal,Mexico city,19.371887,-99.086624,1.0,0,1,1,1,0.0,0.0,1,0,6,Hostage Taking (Kidnapping),7,Government (Diplomatic),45.0,"Diplomatic Personnel (outside of embassy, cons...",Belgian Ambassador Daughter,"Nadine Chaval, daughter",21.0,Belgium,23rd of September Communist League,0.0,0,7.0,0.0,0.0,13,Unknown,Unknown,0.0,0.0,0.0,0.0,0.0,0.0,0,1.0,PGIS,\r
2,197001000001,1970,1,0,0,Philippines,Southeast Asia,Tarlac,Unknown,15.478598,120.599741,4.0,0,1,1,1,0.0,0.0,1,0,1,Assassination,10,Journalists & Media,54.0,Radio Journalist/Staff/Facility,Voice of America,Employee,217.0,United States,Unknown,0.0,0,-99.0,0.0,0.0,13,Unknown,Unknown,1.0,0.0,0.0,0.0,0.0,0.0,0,0.0,PGIS,\r
3,197001000002,1970,1,0,0,Greece,Western Europe,Attica,Athens,37.997490,23.762728,1.0,0,1,1,1,0.0,0.0,1,0,3,Bombing/Explosion,7,Government (Diplomatic),46.0,Embassy/Consulate,Unknown,U.S. Embassy,217.0,United States,Unknown,0.0,0,-99.0,0.0,0.0,6,Explosives,Unknown Explosive Type,0.0,0.0,0.0,0.0,0.0,0.0,1,0.0,PGIS,\r
4,197001000003,1970,1,0,0,Japan,East Asia,Fukouka,Fukouka,33.580412,130.396361,1.0,0,1,1,1,-9.0,0.0,1,0,7,Facility/Infrastructure Attack,7,Government (Diplomatic),46.0,Embassy/Consulate,Unknown,U.S. Consulate,217.0,United States,Unknown,0.0,0,-99.0,0.0,0.0,8,Incendiary,Unknown,0.0,0.0,0.0,0.0,0.0,0.0,1,0.0,PGIS,\r

In [ ]:

# Load country dataset
country_df = pd.read_csv('../datasets/world-data-2023.csv')

print('Country datset columns')
country_df.columns


# Start by removing some of the redudant
columns_to_drop = [
    'Abbreviation', 'Calling Code', 'Capital/Major City', 'Largest city',
    'Population: Labor force participation (%)', 'Urban_population', 'Currency-Code',
    'Gasoline Price', 'Fertility Rate'
]

# Drop the specified columns
country_df = country_df.drop(columns=columns_to_drop)

# Display the first few rows to confirm the columns were dropped
country_df.head()

Country datset columns

,Country,Density\n(P/Km2),Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Co2-Emissions,CPI,CPI Change (%),Forested Area (%),GDP,Gross primary education enrollment (%),Gross tertiary education enrollment (%),Infant mortality,Life expectancy,Maternal mortality ratio,Minimum wage,Official language,Out of pocket health expenditure,Physicians per thousand,Population,Tax revenue (%),Total tax rate,Unemployment rate,Latitude,Longitude
0,Afghanistan,60,58.10%,"652,230","323,000",32.49,"8,672",149.9,2.30%,2.10%,"$19,101,353,833",104.00%,9.70%,47.9,64.5,638.0,$0.43,Pashto,78.40%,0.28,"38,041,754",9.30%,71.40%,11.12%,33.939110,67.709953
1,Albania,105,43.10%,"28,748","9,000",11.78,"4,536",119.05,1.40%,28.10%,"$15,278,077,447",107.00%,55.00%,7.8,78.5,15.0,$1.12,Albanian,56.90%,1.20,"2,854,191",18.60%,36.60%,12.33%,41.153332,20.168331
2,Algeria,18,17.40%,"2,381,741","317,000",24.28,"150,006",151.36,2.00%,0.80%,"$169,988,236,398",109.90%,51.40%,20.1,76.7,112.0,$0.95,Arabic,28.10%,1.72,"43,053,054",37.20%,66.10%,11.70%,28.033886,1.659626
3,Andorra,164,40.00%,468,NaN,7.20,469,NaN,NaN,34.00%,"$3,154,057,987",106.40%,NaN,2.7,NaN,NaN,$6.63,Catalan,36.40%,3.33,"77,142",NaN,NaN,NaN,42.506285,1.521801
4,Angola,26,47.50%,"1,246,700","117,000",40.73,"34,693",261.73,17.10%,46.30%,"$94,635,415,870",113.50%,9.30%,51.6,60.8,241.0,$0.71,Portuguese,33.40%,0.21,"31,825,295",9.20%,49.10%,6.89%,-11.202692,17.873887

In [ ]:
# Check for null values
country_df.isnull().mean() * 100

Country                                     0.000000
Density\n(P/Km2)                            0.000000
Agricultural Land( %)                       3.589744
Land Area(Km2)                              0.512821
Armed Forces size                          12.307692
Birth Rate                                  3.076923
Co2-Emissions                               3.589744
CPI                                         8.717949
CPI Change (%)                              8.205128
Forested Area (%)                           3.589744
GDP                                         1.025641
Gross primary education enrollment (%)      3.589744
Gross tertiary education enrollment (%)     6.153846
Infant mortality                            3.076923
Life expectancy                             4.102564
Maternal mortality ratio                    7.179487
Minimum wage                               23.076923
Official language                           2.564103
Out of pocket health expenditure            3.589744
Physicians per thousand                     3.589744
Population                                  0.512821
Tax revenue (%)                            13.333333
Total tax rate                              6.153846
Unemployment rate                           9.743590
Latitude                                    0.512821
Longitude                                   0.512821
dtype: float64

In [135]:
# Rename the 'country' column in the country dataset to match the terrorism dataset
globalterrorism_df.rename(columns={'country_txt': 'Country'}, inplace=True)

# Merge the datasets on the 'country_txt' column
merged_df = pd.merge(globalterrorism_df, country_df, on='Country', how='left')

# Now you can inspect the merged dataset
merged_df.describe()

,eventid,iyear,imonth,iday,extended,latitude,longitude,specificity,vicinity,crit1,crit2,crit3,doubtterr,multiple,success,suicide,attacktype1,targtype1,targsubtype1,natlty1,guncertain1,individual,nperps,nperpcap,claimed,weaptype1,nkill,nkillus,nkillter,nwound,nwoundus,nwoundte,property,ishostkid,Birth Rate,Infant mortality,Life expectancy,Maternal mortality ratio,Physicians per thousand,Latitude,Longitude
count,1.816910e+05,181691.000000,181691.000000,181691.000000,181691.000000,181691.000000,1.816910e+05,181691.000000,181691.000000,181691.000000,181691.000000,181691.000000,181691.000000,181691.000000,181691.000000,181691.000000,181691.000000,181691.000000,181691.000000,181691.000000,181691.00000,181691.000000,181691.000000,181691.000000,181691.000000,181691.000000,181691.000000,181691.000000,181691.000000,181691.000000,181691.000000,181691.000000,181691.000000,181691.000000,177385.000000,177385.000000,177385.000000,177385.000000,177385.000000,177385.000000,177385.000000
mean,2.002705e+11,2002.638997,6.467277,15.505644,0.045346,23.698173,-4.461064e+02,1.451437,0.068297,0.988530,0.993093,0.875668,-0.523168,0.137772,0.889598,0.036507,3.247547,8.439719,46.288005,127.405975,0.08127,0.002950,-78.527610,-0.937262,0.031592,6.447325,2.266860,0.029671,0.320825,2.883296,0.025076,0.066382,-0.544556,0.058996,22.430731,25.736236,71.616453,170.212306,1.346686,22.859725,27.376788
std,1.325957e+09,13.259430,3.388303,8.814045,0.208063,18.377236,2.021946e+05,0.995416,0.284553,0.106483,0.082823,0.329961,2.455813,0.344662,0.313391,0.187549,1.915772,6.653838,30.184850,88.966272,0.27325,0.054234,169.721125,10.109514,0.872204,2.173435,11.227057,4.564308,3.346474,34.309747,2.453378,1.172976,3.122889,0.461022,8.666184,20.203310,6.562958,230.459136,1.161462,18.434684,59.216634
min,1.970000e+11,1970.000000,0.000000,0.000000,0.000000,-53.154613,-8.618590e+07,1.000000,-9.000000,0.000000,0.000000,0.000000,-9.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,4.000000,0.00000,0.000000,-99.000000,-99.000000,-9.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-9.000000,-9.000000,6.400000,1.400000,52.800000,2.000000,0.010000,-40.900557,-106.346771
25%,1.991021e+11,1991.000000,4.000000,8.000000,0.000000,11.849620,6.655000e+00,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,2.000000,3.000000,23.000000,83.000000,0.00000,0.000000,-99.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,16.030000,10.200000,67.100000,37.000000,0.600000,12.879721,1.659626
50%,2.009022e+11,2009.000000,6.000000,15.000000,0.000000,31.467463,4.324651e+01,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,3.000000,4.000000,35.000000,98.000000,0.00000,0.000000,-99.000000,0.000000,0.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,20.550000,22.500000,71.100000,83.000000,0.910000,28.394857,43.679291
75%,2.014081e+11,2014.000000,9.000000,23.000000,0.000000,34.538561,6.835734e+01,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,3.000000,14.000000,73.000000,168.000000,0.00000,0.000000,-99.000000,0.000000,0.000000,6.000000,2.000000,0.000000,0.000000,2.000000,0.000000,0.000000,1.000000,0.000000,29.080000,38.000000,76.800000,145.000000,1.950000,33.854721,69.345116
max,2.017123e+11,2017.000000,12.000000,31.000000,1.000000,74.633553,1.793667e+02,5.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,9.000000,22.000000,113.000000,1004.000000,1.00000,1.000000,25000.000000,406.000000,1.000000,13.000000,1570.000000,1360.000000,500.000000,8191.000000,751.000000,200.000000,1.000000,1.000000,46.080000,84.500000,84.200000,1150.000000,8.420000,64.963051,178.065032

In [ ]:
# Separate numeric and categorical columns
numeric_columns = merged_df.select_dtypes(include=['float64', 'int64']).columns
categorical_columns = merged_df.select_dtypes(include=['object']).columns

# Fill missing values for numeric columns using mean
merged_df[numeric_columns] = merged_df[numeric_columns].fillna(merged_df[numeric_columns].mean())

# Alternatively, you can fill numeric columns with median if preferred:
# merged_df[numeric_columns] = merged_df[numeric_columns].fillna(merged_df[numeric_columns].median())

# Fill missing values for categorical columns using mode
merged_df[categorical_columns] = merged_df[categorical_columns].apply(lambda x: x.fillna(x.mode()[0]), axis=0)

# Verify that there are no missing values left
print(merged_df.isnull().sum())

eventid                                    0
iyear                                      0
imonth                                     0
iday                                       0
extended                                   0
Country                                    0
region_txt                                 0
provstate                                  0
city                                       0
latitude                                   0
longitude                                  0
specificity                                0
vicinity                                   0
crit1                                      0
crit2                                      0
crit3                                      0
doubtterr                                  0
multiple                                   0
success                                    0
suicide                                    0
attacktype1                                0
attacktype1_txt                            0
targtype1                                  0
targtype1_txt                              0
targsubtype1                               0
targsubtype1_txt                           0
corp1                                      0
target1                                    0
natlty1                                    0
natlty1_txt                                0
gname                                      0
guncertain1                                0
individual                                 0
nperps                                     0
nperpcap                                   0
claimed                                    0
weaptype1                                  0
weaptype1_txt                              0
weapsubtype1_txt                           0
nkill                                      0
nkillus                                    0
nkillter                                   0
nwound                                     0
nwoundus                                   0
nwoundte                                   0
property                                   0
ishostkid                                  0
dbsource                                   0
related\r                                  0
Density\n(P/Km2)                           0
Agricultural Land( %)                      0
Land Area(Km2)                             0
Armed Forces size                          0
Birth Rate                                 0
Co2-Emissions                              0
CPI                                        0
CPI Change (%)                             0
Forested Area (%)                          0
GDP                                        0
Gross primary education enrollment (%)     0
Gross tertiary education enrollment (%)    0
Infant mortality                           0
Life expectancy                            0
Maternal mortality ratio                   0
Minimum wage                               0
Official language                          0
Out of pocket health expenditure           0
Physicians per thousand                    0
Population                                 0
Tax revenue (%)                            0
Total tax rate                             0
Unemployment rate                          0
Latitude                                   0
Longitude                                  0
dtype: int64

In [139]:
# Check for duplicate rows in merged_df
duplicates = merged_df.duplicated().sum()

# Print the number of duplicate rows
print(f"Number of duplicate rows: {duplicates}")

Number of duplicate rows: 0